### ISSUE TITLE
Bug in dark theme

### ISSUE THREAD

**Issue by ashutoshsaboo** [SebTota/QuillSN#1]
Thanks @SebTota for building this, this is the only wysiwyg editor (that I found) closest matching with all the functionalities that I needed! However there's an issue with the dark theme, the default text color (which is black) fades under dark mode not making it visible. The toolbar items also are not visible due to the same reason. Would it be possible for you to fix this @SebTota, so atleast in the current state it can be used? See screenshot below:

<img width="1174" alt="Screenshot 2021-12-14 at 10 11 13 PM" src="https://user-images.githubusercontent.com/9900945/146041079-b77c272d-375c-4abf-b262-8c2c7e87c387.png">

Btw, Quill seem to be back in active development - https://github.com/quilljs/quill - see recent commits from 15 days earlier itself. Would you be willing to update this editor correspondingly as well?

**Comment by SebTota** [comment]
Hello @ashutoshsaboo,
To be completely honest I've stopped using Standard Notes for the time being and have not been actively working on the editors. I can add take a look at this since it seems to be a relatively simple fix, but I will more than likely not be updating the Quill version and adding more features in the near future.
